// nvs bindgen — generate foreign-language client modules for an NvS file.
//
// The generated code routes every call through the JSON stdio bridge
// (`nvs bridge`): the module spawns NvS as a subprocess, evaluates the
// embedded NvS source once, and forwards each call as
// {"call": name, "args": [...]}. Value mapping follows the bridge protocol:
// int/float/string/bool/null/array/hash round-trip; anything else is an
// honest error. NvS runtime errors surface as exceptions in the target
// language.
package tools

import (
	"encoding/base64"
	"fmt"
	"path/filepath"
	"strings"
)

// Bindgen generates a client module in the target language for the NvS
// source in src. srcPath is used only to name the generated module/class.
func Bindgen(target, srcPath, src string) (string, error) {
	exp, err := ExportSource(src)
	if err != nil {
		return "", err
	}
	switch target {
	case "python":
		return bindgenPython(srcPath, src, exp), nil
	default:
		return "", fmt.Errorf("bindgen: unsupported target %q (supported: python)", target)
	}
}

func moduleStem(srcPath string) string {
	base := filepath.Base(srcPath)
	return strings.TrimSuffix(base, filepath.Ext(base))
}

// camelCase turns "my_module" into "MyModule".
func camelCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.' || r == ' '
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	out := strings.Join(parts, "")
	if out == "" {
		return "NvsModule"
	}
	return out
}

// pythonLiteral renders an NvS default-value expression as a Python literal
// when it is a simple literal; ok=false for anything more complex.
func pythonLiteral(nvsSrc string) (string, bool) {
	t := strings.TrimSpace(nvsSrc)
	if t == "null" {
		return "None", true
	}
	if t == "true" {
		return "True", true
	}
	if t == "false" {
		return "False", true
	}
	// integer or float literal
	if _, err := fmt.Sscanf(t, "%d", new(int)); err == nil && isBareNumber(t) {
		return t, true
	}
	// string literal (double-quoted; NvS strings use double quotes)
	if len(t) >= 2 && t[0] == '"' && t[len(t)-1] == '"' {
		return t, true
	}
	return "", false
}

func isBareNumber(t string) bool {
	dots := 0
	for i, r := range t {
		switch {
		case r >= '0' && r <= '9':
		case r == '.' && i > 0:
			dots++
			if dots > 1 {
				return false
			}
		case (r == '-' || r == '+') && i == 0:
		default:
			return false
		}
	}
	return len(t) > 0
}

func bindgenPython(srcPath, src string, exp *Exports) string {
	stem := moduleStem(srcPath)
	cls := camelCase(stem)
	encoded := base64.StdEncoding.EncodeToString([]byte(src))

	var b strings.Builder
	fmt.Fprintf(&b, `"""Auto-generated NvS binding for %s — DO NOT EDIT.

Generated by: nvs bindgen --to=python %s
Each method calls through to NvS via the JSON stdio bridge (nvs bridge):
the NvS source is embedded below (base64), evaluated once at startup,
and every call is forwarded as {"call": name, "args": [...]}.

Value mapping: int, float, string, bool, None, list, dict round-trip.
NvS runtime errors raise NvSError.
"""

import base64
import json
import os
import subprocess

_NVS_SOURCE = base64.b64decode(%q).decode("utf-8")


class NvSError(Exception):
    """An error raised inside NvS (parse error, runtime error, or an
    NvS value that cannot be represented in JSON)."""


class _NvsBridge:
    """One persistent `+"`nvs bridge`"+` subprocess."""

    def __init__(self, nvs_bin):
        self._proc = subprocess.Popen(
            [nvs_bin, "bridge"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            bufsize=1,
        )
        self._next_id = 0
        self._request({"eval": _NVS_SOURCE}, "init")

    def _request(self, payload, what):
        self._next_id += 1
        payload = dict(payload)
        payload["id"] = self._next_id
        try:
            self._proc.stdin.write(json.dumps(payload) + "\n")
            self._proc.stdin.flush()
        except BrokenPipeError:
            raise NvSError("nvs bridge subprocess died (while %%s)" %% what)
        line = self._proc.stdout.readline()
        if not line:
            raise NvSError("nvs bridge subprocess closed stdout (while %%s)" %% what)
        try:
            resp = json.loads(line)
        except json.JSONDecodeError as e:
            raise NvSError("nvs bridge returned invalid JSON (while %%s): %%s" %% (what, e))
        if not resp.get("ok", False):
            raise NvSError(resp.get("error", "unknown nvs error"))
        return resp.get("result")

    def call(self, name, args):
        return self._request({"call": name, "args": list(args)}, "call %%s" %% name)

    def close(self):
        try:
            if self._proc.stdin:
                self._proc.stdin.close()
        finally:
            self._proc.wait(timeout=10)

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


class %s:
    """Python client for the NvS module %s."""

    def __init__(self, nvs_bin=None):
        """nvs_bin: path to the nvs binary (default: $NVS_BIN or "nvs"
        resolved via PATH)."""
        nvs_bin = nvs_bin or os.environ.get("NVS_BIN", "nvs")
        self._bridge = _NvsBridge(nvs_bin)

`, stem, srcPath, quotedPy(encoded), cls, stem)

	for _, fn := range exp.Functions {
		if fn.Kind == "generator" {
			fmt.Fprintf(&b, "    # NOTE: %s is an NvS generator function; calling it returns\n", fn.Name)
			fmt.Fprintf(&b, "    # the collected values as a list (NvS generators are eager).\n")
		}
		var sig []string
		for _, p := range fn.Params {
			if lit, ok := pythonLiteral(deref(p.Default)); ok && !p.Required {
				sig = append(sig, fmt.Sprintf("%s=%s", p.Name, lit))
			} else {
				sig = append(sig, p.Name)
			}
		}
		fmt.Fprintf(&b, "    def %s(self%s):\n", fn.Name, prependComma(strings.Join(sig, ", ")))
		fmt.Fprintf(&b, "        \"\"\"NvS: %s(%s)", fn.Name, strings.Join(paramNames(fn.Params), ", "))
		if fn.ReturnType != nil {
			fmt.Fprintf(&b, " -> %s", *fn.ReturnType)
		}
		fmt.Fprintf(&b, " [arity %d, %d required]\"\"\"\n", fn.Arity, fn.Required)
		fmt.Fprintf(&b, "        return self._bridge.call(%q, [%s])\n\n",
			fn.Name, strings.Join(paramNames(fn.Params), ", "))
	}

	fmt.Fprintf(&b, `    def close(self):
        """Shut down the NvS subprocess."""
        self._bridge.close()

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()
`)
	return b.String()
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

func paramNames(ps []ParamExport) []string {
	out := make([]string, len(ps))
	for i, p := range ps {
		out[i] = p.Name
	}
	return out
}

func prependComma(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}

// quotedPy renders s as a Python string literal (double-quoted, escaped).
func quotedPy(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
